project:
  type: website
  output-dir: docs

website:
  title: "LGBTQ+ Representation in Television Series"

format:
  html:
    theme: quarto/custom.scss
    toc: false
    code-fold: true
    code-summary: "Code anzeigen"
    smooth-scroll: true

execute:
  echo: true
  warning: false
  message: false
  eval: false

jupyter: python3

resources:
  - assets/**
  - images/**
  - visualizations/**
  - plots/**
  - scrollspy.js

header-includes: |
  <meta name="quarto:offset" content="140">